language: d
sudo: false
dist: xenial

matrix:
  include:
    - d: dmd-nightly
    - d: dmd-2.083.0
  allow_failures:
    - d: dmd-nightly


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libclang-6.0-dev
      - g++-7


install:
  - gem install bundler
  - bundle install


script:
  - apt-cache search libclang
  - find / -name 'libclang*so' 2> /dev/null
  - ./ci.sh


after_success:
 - bash <(curl -s https://codecov.io/bash)
