language: d
sudo: false

addons:
  apt:
    packages:
      - libclang-3.9-dev


install:
  - gem install bundler
  - bundle install



script:
  - dub test
  - dub build
  - ./examples.sh
  - bundle exec cucumber --tags ~@wip
