language: d
sudo: false


addons:
  apt:
    packages:
      - libclang-3.9-dev


install:
  - gem install bundler
  - bundle install


script:
  - dub test --build=unittest-cov --compiler=${DC}
  - dub build
  - bundle exec cucumber --tags ~@wip
  # - ./examples.sh


after_success:
 - bash <(curl -s https://codecov.io/bash)
