language: d
sudo: false


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libclang-3.9-dev
      - g++-7


install:
  - gem install bundler
  - bundle install


script:
  - ./ci.sh

after_success:
 - bash <(curl -s https://codecov.io/bash)
