language: d
sudo: false

matrix:
  include:
    - d: dmd-nightly
    - d: dmd-2.081.2
    - d: dmd-2.080.1
    - d: dmd-2.079.1
    - d: ldc-1.10.0
    - d: ldc-1.9.0
    - d: ldc-1.8.0
  allow_failures:
    - d: dmd-nightly


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libclang-3.9-dev
      - g++-7

install:
  - gem install bundler
  - bundle install


script:
  - ./ci.sh

after_success:
 - bash <(curl -s https://codecov.io/bash)
