language: d
sudo: false


addons:
  apt:
    packages:
      - libclang-3.9-dev


install:
  - gem install bundler
  - bundle install


script:
  - ./ci.sh

after_success:
 - bash <(curl -s https://codecov.io/bash)
